name: Orbit-db Kuiper tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests-et-couverture:
    name: Node.js test
    runs-on: ubuntu-latest
    steps:
      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installer pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Nétoyer les dépendances d'installation
        run: pnpm install --lockfile=false

      - name: Vérifier les tests
        run: pnpm test

      - name: Envoyer couverture à Codecov
        uses: codecov/codecov-action@v3
